# duplicated with minor edits from https://jekyllrb.com/docs/continuous-integration/github-actions/
name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        with:
          jekyll_src: 'site'
          target_branch: 'gh-pages'
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
